config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :registrations => 'admins/registrations',
    :sessions => 'admins/sessions',
    :passwords => 'admins/passwords'
  }

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :omniauth_callbacks => 'users/omniauth_callbacks' }

    # 管理者側ページへ名前空間設定：admin
  namespace :admin do
    get '/top', to: 'tops#top'

    resources :users, only: [:index, :show, :destroy, :restore]
    get 'admin/users/:id/restore' => 'users#restore', as: 'user_restore' # 論理削除で退会させた人を復元させる

    resources :reports, only: [:index, :destroy]
    resources :messages, only: [:index]
  end

    # 論理削除後にログイン状態を維持してしまうので、強制ログアウトを行う
  devise_scope :user do
    get '/logout', to: 'users/sessions#destroy', as: "logout"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tops#top'
  get '/rules' => 'abouts#rules'
  post '/teacher_requests' => 'requests#create_2'

	resources :users do
    resources :requests, shallow: true, only: [:index, :update, :destroy]
    resources :reports, except: [:edit, :destroy]
    resources :rooms, shallow: true
    resources :reservations, shallow: true
    resources :students, shallow: true, except: [:index] do
      resource :favorites, only: [:create, :destroy]
      resource :requests, only: [:create]
    end
  	resources :teachers, shallow: true, except: [:index] do
 		  resource :favorites, only: [:create, :destroy]
      resource :requests, only: [:create]
    end
  end

  resources :rooms, except: [:index] do
    resources :messages, shallow: true, except: [:edit]
  end

  resources :students, only: [:index]
  resources :teachers, only: [:index]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :users
  has_many :user_areas, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :language_teachers
  has_many :teachers, through: :language_teachers
  has_many :language_students
  has_many :students, through: :language_students
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  validates :comment, presence: true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
  enum status: {保留: 0,
  			  承認: 1,
  			  拒否: 2
  			  }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
  enum status: {予定: 0,
  			    終了: 1
  			   }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  has_many :messages
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :teachers, through: :requests
  has_many :rooms
  has_many :reservations
  has_many :teachers, through: :reservations
  has_many :language_students
  has_many :languages, through: :language_students
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :language_students, allow_destroy: true
  enum japanese_level: {話せない: 0,日常会話レベル: 1,ビジネスレベル: 2,ネイティブレベル: 3}


  validates :message, presence: true, length: { maximum: 250}
  validates :what_to_learn, presence: true, length: { maximum: 250}

  paginates_per 12

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :students, through: :requests
  has_many :rooms
  has_many :reservations
  has_many :students, through: :reservations
  has_many :language_teachers
  has_many :languages, through: :language_teachers
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :language_teachers, allow_destroy: true
  enum japanese_level: {話せない: 0,日常会話レベル: 1,ビジネスレベル: 2,ネイティブレベル: 3}

  validates :message, presence: true, length: { maximum:250}
  validates :background, length: { maximum:250}
  validates :detailed_place_1, presence: true
  validates :detailed_address_1, presence: true

  paginates_per 12

  def favorited_by?(student)
    favorites.where(student_id: student.id).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  attachment :image
  enum gender: {男性: 0,
  				      女性: 1}
  has_one :teacher
  has_one :student
  has_many :reservations, through: :students
  has_many :reservations, through: :teachers
  has_many :rooms, through: :students
  has_many :rooms, through: :teachers
  has_many :user_areas, dependent: :destroy
  has_many :areas, through: :user_areas
  has_many :reports
  accepts_nested_attributes_for :user_areas, allow_destroy: true


  # validates :image, presence: true
  # validates :nationality, presence: true, length: { maximum: 50}
  # validates :nickname, presence: true, length: { maximum: 15}

  soft_deletable

  def self.find_for_database_authentication(warden_conditions)
    without_soft_destroyed.where(email: warden_conditions[:email]).first
  end

  def self.find_for_google_oauth2(auth)
    user = User.where(email: auth.info.email).first
    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20])
     end
     user
  end

end

app/models/user_area.rb
class UserArea < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :area, optional: true
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/tops.html.erb
<div class="top_image_box">
	<div class="top_image">
			<div class="top_logo_box">
				<%= image_tag("logo_black.png", :class => "top_logo") %>
			</div>
				<div class="top_image_text_left">
					<div class="line1">Welcome administrators!</div>
					<div class="line2">Keep it up!</div>
				</div>
				<div class="top_image_text_right">
					<div class="top_image_text_1">\ Hello　Admin! /</div>
				</div>
		<div class="col-lg-8 col-lg-offset2"%>
				<div class="top_top">
					<div class="top_subtitle">
						<p>アドミン用</p>
					</div>

						<div class="top_box_3">
							<%= link_to new_admin_session_path do %>
								<div class="top_text_3">
									Log In
								</div>
							<% end %>
						</div>
						<div class="top_box_4">
							<%= link_to new_admin_registration_path do %>
								<div class="top_text_4">
									Sign Up
								</div>
							<% end %>
						</div>
						<%= link_to 'Signin with Google', user_omniauth_authorize_path(:google_oauth2) %>
				</div>
		</div>
	</div>
</div>

app/views/shared/_category.html.erb
<% if admin_signed_in? %>
	<div class="container-fluid">
	    <div class="col-lg-2">
	    	<div class="side-bar">
	    		<div class="side_logo_box">
					<%= link_to image_tag("logo_black.png", :class => 'about_logo'), admin_top_path %>
				</div>
			</div>
	    	 	<div class="category_box">
			    	<h4 style="padding-left:26px;">My Menu</h4>
			    	<ul class="category">
				    	<li class="category_list">
				    		<%= link_to "ユーザ情報", admin_users_path %>
				    	</li>
				    	<li class="category_list">
				    		<%= link_to "通報一覧", admin_reports_path %>
				    	</li>
				    	<li class="category_list">
				    		<%= link_to "ユーザメッセージ一覧", admin_messages_path %>
				    	</li>
				    	<li class="category_list">
							<%= link_to "ログアウト", destroy_admin_session_path, method: :delete%>
						</li>
				    </ul>
		    	</div>
		    	<div class="category_img">
		    		<%= image_tag("office.jpeg", :class => 'office_img') %>
		    	</div>
		</div>
<% else %>
<header>
<div class="header_bar">
  <div id="nav-drawer">
	<div class="navToggle">
    	<span></span><span></span><span></span><span>menu</span>
	</div>
	<nav class="globalMenuSp">
	    <ul>
			<li class="category_list">
	    		<%= link_to "ユーザ情報", user_path(current_user) %>
	    	</li>
	    	<li class="category_list">
	    		<%= link_to "生徒情報", student_path(current_user) %>
	   		</li>
	    	<li class="category_list">
	    		<%= link_to "先生情報", teacher_path(current_user) %>
	    	</li>
	    	<li class="category_list">
	    		<%= link_to "予約一覧", user_reservations_path(current_user) %>
	    	</li>
	    	<li class="category_list">
	    		<%= link_to "メッセージ一覧", user_rooms_path(current_user) %>
	    	</li>
	    	<li class="category_list">
	    		<%= link_to "メッセージリクエスト一覧", user_requests_path(current_user) %>
	    	</li>
	    	<li class="category_list">
				<%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
			</li>
	    </ul>
	</nav>
  </div>
</div>
</header>
	<div class="container-fluid">
	    <div class="col-lg-2">
	    	<div class="side-bar">
	    		<div class="side_logo_box">
					<%= link_to image_tag("logo_black.png", :class => 'about_logo'), root_path %>
				</div>
				<%= link_to students_path do %>
					<div class="find_s_box">
						生徒を探す
					</div>
				<% end %>
				<%= link_to teachers_path do %>
					<div class="find_t_box">
						先生を探す
					</div>
				<% end %>
			</div>
	    	 	<div class="category_box">
			    	<h4 style="padding-left:26px;">My Menu</h4>
			    	<ul class="category">
				    	<li class="category_list">
				    		<%= link_to "ユーザ情報", user_path(current_user) %>
				    	</li>
				    	<li class="category_list">
				    		<%= link_to "生徒情報", student_path(current_user) %>
				   		</li>
				    	<li class="category_list">
				    		<%= link_to "先生情報", teacher_path(current_user) %>
				    	</li>
				    	<li class="category_list">
				    		<%= link_to "予約一覧", user_reservations_path(current_user) %>
				    	</li>
				    	<li class="category_list">
				    		<%= link_to "メッセージ一覧", user_rooms_path(current_user) %>
				    	</li>
				    	<li class="category_list">
				    		<%= link_to "メッセージリクエスト一覧", user_requests_path(current_user) %>
				    	</li>
				    	<li class="category_list">
							<%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
						</li>
				    </ul>
		    	</div>
		    	<div class="category_img">
		    		<%= image_tag("office.jpeg", :class => 'office_img') %>
		    	</div>
		</div>
<% end %>