config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :registrations => 'admins/registrations',
    :sessions => 'admins/sessions',
    :passwords => 'admins/passwords'
  }

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :omniauth_callbacks => 'users/omniauth_callbacks' }

    # 管理者側ページへ名前空間設定：admin
  namespace :admin do
    get '/top', to: 'tops#top'

    resources :users, only: [:index, :show, :destroy, :restore]
    get 'admin/users/:id/restore' => 'users#restore', as: 'user_restore' # 論理削除で退会させた人を復元させる

    resources :reports, only: [:index, :destroy]
    resources :messages, only: [:index]
  end

    # 論理削除後にログイン状態を維持してしまうので、強制ログアウトを行う
  devise_scope :user do
    get '/logout', to: 'users/sessions#destroy', as: "logout"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tops#top'
  get '/rules' => 'abouts#rules'
  post '/teacher_requests' => 'requests#create_2'

	resources :users do
    resources :requests, shallow: true, only: [:index, :update, :destroy]
    resources :reports, except: [:edit, :destroy]
    resources :rooms, shallow: true
    resources :reservations, shallow: true
    resources :students, shallow: true, except: [:index] do
      resource :favorites, only: [:create, :destroy]
      resource :requests, only: [:create]
    end
  	resources :teachers, shallow: true, except: [:index] do
 		  resource :favorites, only: [:create, :destroy]
      resource :requests, only: [:create]
    end
  end

  resources :rooms, except: [:index] do
    resources :messages, shallow: true, except: [:edit]
  end

  resources :students, only: [:index]
  resources :teachers, only: [:index]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :users
  has_many :user_areas, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :language_teachers
  has_many :teachers, through: :language_teachers
  has_many :language_students
  has_many :students, through: :language_students
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  validates :comment, presence: true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
  enum status: {保留: 0,
  			  承認: 1,
  			  拒否: 2
  			  }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
  enum status: {予定: 0,
  			    終了: 1
  			   }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  has_many :messages
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :teachers, through: :requests
  has_many :rooms
  has_many :reservations
  has_many :teachers, through: :reservations
  has_many :language_students
  has_many :languages, through: :language_students
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :language_students, allow_destroy: true
  enum japanese_level: {話せない: 0,日常会話レベル: 1,ビジネスレベル: 2,ネイティブレベル: 3}


  validates :message, presence: true, length: { maximum: 250}
  validates :what_to_learn, presence: true, length: { maximum: 250}

  paginates_per 12

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :students, through: :requests
  has_many :rooms
  has_many :reservations
  has_many :students, through: :reservations
  has_many :language_teachers
  has_many :languages, through: :language_teachers
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :language_teachers, allow_destroy: true
  enum japanese_level: {話せない: 0,日常会話レベル: 1,ビジネスレベル: 2,ネイティブレベル: 3}

  validates :message, presence: true, length: { maximum:250}
  validates :background, length: { maximum:250}
  validates :detailed_place_1, presence: true
  validates :detailed_address_1, presence: true

  paginates_per 12

  def favorited_by?(student)
    favorites.where(student_id: student.id).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  attachment :image
  enum gender: {男性: 0,
  				      女性: 1}
  has_one :teacher
  has_one :student
  has_many :reservations, through: :students
  has_many :reservations, through: :teachers
  has_many :rooms, through: :students
  has_many :rooms, through: :teachers
  has_many :user_areas, dependent: :destroy
  has_many :areas, through: :user_areas
  has_many :reports
  accepts_nested_attributes_for :user_areas, allow_destroy: true


  # validates :image, presence: true
  # validates :nationality, presence: true, length: { maximum: 50}
  # validates :nickname, presence: true, length: { maximum: 15}

  soft_deletable

  def self.find_for_database_authentication(warden_conditions)
    without_soft_destroyed.where(email: warden_conditions[:email]).first
  end

  def self.find_for_google_oauth2(auth)
    user = User.where(email: auth.info.email).first
    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20])
     end
     user
  end

end

app/models/user_area.rb
class UserArea < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :area, optional: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :correct_user, only: [:edit]
  protect_from_forgery :except => [:create]

  def new
    @user = User.find(params[:user_id])
    if @user.nickname.present? && @user.nationality.present?
      @student = Student.new
      @student.language_students.build
    else
      redirect_to edit_user_path(current_user), flash: {alert: "すべてのユーザ情報を登録してください"}
    end
  end

  def create
    @user = current_user
    @student = Student.new(student_params)
    @student.id = current_user.id
    if @student.save
      redirect_to student_path(current_user)
    else
      render :new
    end
  end

  def index
    @requests = Request.all
    @q = Student.ransack(params[:q])
    if params[:q].present?
      @students = @q.result(distinct: true).where.not(id: current_user).page(params[:page]).reverse_order
    else
      @students = Student.where.not(id: current_user).page(params[:page]).reverse_order
    end
    @request_s = Request.new
  end

  def show
    if Student.exists?(id: params[:id])
      @student = Student.find(params[:id])
    end
  end

  def edit
    @student = Student.find(params[:id])
    unless @student.language_students.exists?
      @student.language_students.build
    end
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to student_path(@student.id)
  end



  private
  def student_params
    params.require(:student).permit(
									:budget,
									:first_language,
									:message,
									:user_id,
									:what_to_learn,
									:other_language,
									language_students_attributes: [:id, :language_id, :_destroy]
								   )
  end

  def correct_user
    @student = Student.find(params[:id])
      unless current_user.id == @student.id
        redirect_to student_path(current_user)
      end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/students/edit.html.erb
<%= render 'shared/category', user: @user, student: @student %>
	<div class="col-lg-8">
		<div class="user_info">
			<div class="user_info_text">
				<h2>生徒情報更新</h2>
			</div>
	    		<%= form_for(@student, url: student_path) do |f| %>
					<div class="container">
			   				    <div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>勉強する言語</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
									   		    <%= nested_form_for @student do |n| %>
											        	<%= n.fields_for :language_students do |ls| %>
										        			<%= ls.collection_select :language_id, Language.all, :id, :language_name,　class: "form-control" %>
										        			<%= ls.link_to_remove "削除" %>
										        		<% end %>
										        		<%= n.link_to_add "言語追加", :language_students %>
												<% end %>
							    			</div>
					    			</div>
					    		</div>
					    		<div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>勉強するその他の言語</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
					    						<%= f.text_field :other_language, class: "form-control", placeholder:"例:タガログ、モンゴル", style:"width:300px; margin:0 auto;"  %>
							    			</div>
					    			</div>
					    		</div>
								<div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>母国語</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
				        						<%= f.collection_select(:first_language, Language.all, :language_name, :language_name) %>
						    				</div>
					    			</div>
					    		</div>
								<div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>値段 / 1h</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
					        					<%= f.select :budget, {"1500円" => "1500", "2000円" => "2000", "2500円" => "2500", "3000円" => "3000", "3500円" => "3500", "4000円" => "4000", "4500円" => "4500", "5000円" => "5000"} %>
							    			</div>
					    			</div>
					    		</div>
								<div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>メッセージ</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
												<%= f.text_area :message, class: "form-control", placeholder:"Message" %>
							    			</div>
					    			</div>
					    		</div>
								<div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>学びたいこと</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
						    					<%= f.text_area :what_to_learn, class: "form-control" %>
								        	<%= f.hidden_field :user_id, :value => current_user.id %>
								            <%= f.submit "送信", class: "btn btn-black" %>
								           	</div>

								    </div>
					            </div>
					</div>
		        <% end %>
			</div>
		</div>
	</div>
<!-- 部分テンプレート閉じタグ -->
</div>

app/views/students/index.html.erb
<%= render 'shared/category' %>
	<div class="col-lg-8">
		<div class="mobile_search_button">
			<button type="button" class="btn btn-success" data-toggle="collapse" data-target="#mobile_search" style="width: 100%;" >
				<p style="text-align:center; margin:0 auto;">生徒を絞込検索</p>
			</button>
		</div>
		<div id="mobile_search" class="collapse">
			<div class="dropdown">
				<div class="mobile_search_box">
				<%= search_form_for(@q, :url => {:controller => '/students', :action => 'index'}) do |f| %>
					<div class="col-lg-12">
						<div class="col-lg-5">
							<h5>地域で探す</h5>
								<%= f.collection_select :user_areas_id_eq, Area.all, :id, :area_name, include_blank: '選択してください' %>
						</div>
						<div class="col-lg-4">
							<h5>言語で探す</h5>
								<%= f.collection_radio_buttons :languages_id_in, Language.all, :id, :language_name %>
							<h5>その他の言語</h5>
							<div class="form-inline">
								<%= f.search_field :other_language_cont, class: "form-control search_form", placeholder: "例:タガログ" %>語
							</div>
						</div>
						<div class="col-lg-3">
							<h5>予算を選択(/1h)</h5>
							<div class="select">
								<%= f.select :budget_eq, {"1500円" => "1500", "2000円" => "2000", "2500円" => "2500", "3000円" => "3000", "3500円" => "3500", "4000円" => "4000", "4500円" => "4500", "5000円" => "5000"}, include_blank: '選択してください' %>
							</div>
           				     	<%= button_tag :type => "submit", :class =>" search-button fa fa-search" do %>
				      			<% end %>
			      		</div>
			      	</div>
			 		<% end %>
			 	</div>
		 	</div>
		</div>
		<div class="search_box">
				<%= search_form_for(@q, :url => {:controller => '/students', :action => 'index'}) do |f| %>
				<h4 style="margin:0 auto;">生徒を検索</h4>
				<div class="col-lg-12">
					<div class="col-lg-5">
						<h5>地域で探す</h5>
							<%= f.collection_select :user_areas_id_eq, Area.all, :id, :area_name, include_blank: '選択してください' %>
					</div>
					<div class="col-lg-4">
						<h5>言語で探す</h5>
							<%= f.collection_radio_buttons :languages_id_in, Language.all, :id, :language_name %>
						<h5>その他の言語</h5>
						<div class="form-inline">
							<%= f.search_field :other_language_cont, class: "form-control search_form", placeholder: "例:タガログ" %>語
						</div>
					</div>
					<div class="col-lg-3">
						<h5>予算を選択(/1h)</h5>
						<div class="select">
							<%= f.select :budget_eq, {"1500円" => "1500", "2000円" => "2000", "2500円" => "2500", "3000円" => "3000", "3500円" => "3500", "4000円" => "4000", "4500円" => "4500", "5000円" => "5000"}, include_blank: '選択してください' %>
						</div>
       				     	<%= button_tag :type => "submit", :class =>" search-button fa fa-search" do %>
			      			<% end %>
		      		</div>
		      	<% end %>
		       </div>
		</div>
		<% if @students.present? %>
			<% @students.each do |s| %>
					<div class="col-lg-4">
						<div class="index_box">
							<div class="index_img">
							<%= link_to student_path(s) do %>
								<%= attachment_image_tag s.user,:image, class:"index_img", fallback: "No_img.jpg" %>
							<% end %>
							</div>
							<table>
								<tr>
									<td><div class="fa fa-user"><%= s.user.nickname %></td>
								</tr>
								<tr>
									<td><div class="message_container">
										<div class="fa fa-comment"><%= truncate(s.message, length: 50) %>
									</div></td>
								</tr>
								<tr>
									<td>
										値段：<%= s.budget %>円(1h)
									</td>
								<tr>
								<tr>
									<td>
										言語:
										<% s.language_students.each do |ls| %>
										<%= ls.language.language_name %>,
										<% end %>
									</td>
								</tr>
								<tr>
									<td>
										<% unless @requests.exists?(teacher_id: current_user.id, student_id: s.id) %>
											<%= form_for(@request_s, url: student_requests_path(s.id), method: :post) do |f| %>
											<%= f.hidden_field :teacher_id, :value => current_user.id %>
											<%= f.hidden_field :student_id, :value => s.id %>
											<%= f.hidden_field :status, :value => "保留" %>
											<%= f.hidden_field :receiver_id, :value => s.id %>
											<%= f.hidden_field :send_user_id, :value => current_user.id %>
											<%= f.submit "メッセージリクエストを送る", class:"btn btn-blue" %>
											<% end %>
										<% else %>
											<div class="requested_button">
												<h5>メッセージリクエスト受信・送信済</h5>
											</div>
										<% end %>
									</td>
								</tr>
							</table>
						</div>
					</div>
			<% end %>
			<div class="pagination">
				<%= paginate @students %>
			</div>
			<% else %>
				<div class="flash_message">
					条件に合う生徒は見つかりませんでした
				</div>
			<% end %>
	</div>

app/views/students/new.html.erb
<%= render 'shared/category', user: @user, student: @student %>
<div class="col-lg-8">
		<div class="user_info">
			<div class="user_info_text">
				<h2>生徒情報登録</h2>
			</div>
			<% if @student.errors.any? %>
			 　<script type="text/javascript">
			 　　<% @student.errors.full_messages.each do |f| %>
			　　　　　toastr['<%='error'%>']('<%=f %>');
			 　　<% end %>
			 <% end %>
			　　</script>
   	    		<%= form_for(@student, url: user_students_path) do |f| %>
					<div class="container">
			   				    <div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>勉強する言語</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
									   		    <%= nested_form_for @student do |n| %>
											        	<%= n.fields_for :language_students do |ls| %>
										        			<%= ls.collection_select :language_id, Language.all, :id, :language_name,　class: "form-control" %>
										        			<%= ls.link_to_remove "削除" %>
										        		<% end %>
										        		<%= n.link_to_add "言語追加", :language_students %>
												<% end %>
							    			</div>
							    	</div>
							    </div>
					     		<div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>勉強するその他の言語</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
					    						<%= f.text_field :other_language, class: "form-control", placeholder:"例:タガログ、モンゴル", style: "width:300px; margin:0 auto;"  %>
							    			</div>
					    			</div>
			    				</div>
								<div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>母国語</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
				        						<%= f.collection_select(:first_language, Language.all, :language_name, :language_name) %>
						    				</div>
					    			</div>
					    		</div>
								<div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>値段 / 1h</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
					        					<%= f.select :budget, {"1500円" => "1500", "2000円" => "2000", "2500円" => "2500", "3000円" => "3000", "3500円" => "3500", "4000円" => "4000", "4500円" => "4500", "5000円" => "5000"} %>
							    			</div>
					    			</div>
					    		</div>
								<div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>メッセージ</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
												<%= f.text_area :message, class: "form-control" %>
							    			</div>
					    			</div>
					    		</div>
								<div class="col-sm-8  col-sm-offset-2">
							        <div class="form-group">
				   				    		<div class="col-sm-3">
					   				    		<label>学びたいこと</label>
					   				    	</div>
					   				    	<div class="col-sm-9">
						    					<%= f.text_area :what_to_learn, class: "form-control" %>
							    			<%= f.hidden_field :user_id, :value => current_user.id %>
								            <%= f.submit "送信", class: "btn btn-black" %>
								           	</div>
						           	</div>
					            </div>
					</div>
		        <% end %>
			</div>
		</div>
	</div>
<!-- 部分テンプレート閉じタグ -->
</div>

app/views/students/show.html.erb
<%= render 'shared/category' %>
<div class="col-lg-10">
	<% if Student.exists?(id: params[:id]) %>
		<div class="student_info">
			<div class="student_info_text">
				<h2><i class="fa fa-address-card icon-color"></i><%= @student.user.nickname %>さんの生徒情報</h2>
			</div>
			<div class="col-lg-5">
				<div class="user_img">
					<%= attachment_image_tag @student.user,:image %>
					<% if @student.id == current_user.id %>
						<%= link_to edit_student_path(current_user) do %>
							<div class="btn btn-black">編集</div>
						<% end %>
					<% else %>
					<div class="last_login">
						最終ログイン日:<%= @student.user.last_sign_in_at.strftime('%Y/%m/%d') %>
					</div>
					<% end %>
				</div>
			</div>
			<div class="col-lg-7">
				<div class="s-header">
					<% @student.user.user_areas.each do |s| %>
						<h5>
							<div class="area_box">
								<%= s.area.area_name %><br>
								<%= s.area.area_name_eng %>
							</div>
						</h5>
					<% end %>
				</div>
				<div class="col-lg-12 s-information">
					<div class="col-lg-4">
				        <h3><i class="fa fa-book icon-color"></i>勉強する言語</h3>
			        		<% if @student.other_language.present? %>
			        			<h5><%= @student.other_language %>語</h5>
			        		<% end %>
				        	<% @student.language_students.each do |ls| %>
						        	<h5><%= ls.language.language_name %></h5>
				        	<% end %>
				     </div>
				     <div class="col-lg-4">
				        <h3><i class="fa fa-eye icon-color"></i>値段</h3>
				        	<h5>¥<%= number_with_delimiter(@student.budget) %></h5>
				     </div>
				     <div class="col-lg-4">
				     		<h3><i class="fa fa-comment icon-color"></i>母国語</h3>
				     	<h5><%= @student.first_language %></h5>
				     </div>
				</div>
				<div class="col-lg-12 s-message">
					<h3>メッセージ</h3>
						<h5><%= @student.message %></h5>
				</div>
				<div class="col-lg-12 s-what_to_learn">
					<h3>学びたいこと</h3>
						<h5><%= @student.what_to_learn %></h5>
				</div>
			</div>
		</div>
	<% else %>
		<div class="user_info">
		<div class="user_info_text">
			登録された生徒情報がありません。
			<%= link_to new_user_student_path(current_user) do %>
			<p>生徒情報登録</p>
			<% end %>
		</div>
		</div>
	<% end %>
</div>
<!-- container-fluid divタグ閉じ -->
</div>