config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :registrations => 'admins/registrations',
    :sessions => 'admins/sessions',
    :passwords => 'admins/passwords'
  }

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :omniauth_callbacks => 'users/omniauth_callbacks' }

    # 管理者側ページへ名前空間設定：admin
  namespace :admin do
    get '/top', to: 'tops#top'

    resources :users, only: [:index, :show, :destroy, :restore]
    get 'admin/users/:id/restore' => 'users#restore', as: 'user_restore' # 論理削除で退会させた人を復元させる

    resources :reports, only: [:index, :destroy]
    resources :messages, only: [:index]
  end

    # 論理削除後にログイン状態を維持してしまうので、強制ログアウトを行う
  devise_scope :user do
    get '/logout', to: 'users/sessions#destroy', as: "logout"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tops#top'
  get '/rules' => 'abouts#rules'
  post '/teacher_requests' => 'requests#create_2'

	resources :users do
    resources :requests, shallow: true, only: [:index, :update, :destroy]
    resources :reports, except: [:edit, :destroy]
    resources :rooms, shallow: true
    resources :reservations, shallow: true
    resources :students, shallow: true, except: [:index] do
      resource :favorites, only: [:create, :destroy]
      resource :requests, only: [:create]
    end
  	resources :teachers, shallow: true, except: [:index] do
 		  resource :favorites, only: [:create, :destroy]
      resource :requests, only: [:create]
    end
  end

  resources :rooms, except: [:index] do
    resources :messages, shallow: true, except: [:edit]
  end

  resources :students, only: [:index]
  resources :teachers, only: [:index]

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :students, through: :requests
  has_many :rooms
  has_many :reservations
  has_many :students, through: :reservations
  has_many :language_teachers
  has_many :languages, through: :language_teachers
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :language_teachers, allow_destroy: true
  enum japanese_level: {話せない: 0,日常会話レベル: 1,ビジネスレベル: 2,ネイティブレベル: 3}

  validates :message, presence: true, length: { maximum:250}
  validates :background, length: { maximum:250}
  validates :detailed_place_1, presence: true
  validates :detailed_address_1, presence: true

  paginates_per 12

  def favorited_by?(student)
    favorites.where(student_id: student.id).exists?
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :correct_user, only: [:edit]
  protect_from_forgery :except => [:create]

  def new
    @user = User.find(params[:user_id])
    if @user.nickname.present? && @user.nationality.present?
      @teacher = Teacher.new
      @teacher.language_teachers.build
    else
      redirect_to edit_user_path(current_user), flash: {alert: "すべてのユーザ情報を登録してください"}
    end
  end

  def index
    @languages = Language.all
    @requests = Request.all
    @q = Teacher.ransack(params[:q])
    if params[:q].present?
      @teachers = @q.result.where.not(id: current_user).page(params[:page]).reverse_order
    else
      @teachers = Teacher.where.not(id: current_user).page(params[:page]).reverse_order
    end
    @request_t = Request.new
  end

  def create
    @user = current_user
    @teacher = Teacher.new(teacher_params)
    @teacher.id = current_user.id
    if @teacher.save
      redirect_to teacher_path(current_user)
    else
      render :new
    end
  end

  def show
    if Teacher.exists?(id: params[:id])
      @teacher = Teacher.find(params[:id])
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
    unless @teacher.language_teachers.exists?
      @teacher.language_teachers.build
    end
  end

  def update
    @teacher = Teacher.find(params[:id])
    @teacher.update(teacher_params)
    redirect_to teacher_path(@teacher)
  end

  private
  def teacher_params
    params.require(:teacher).permit(
										:user_id,
										:budget,
										:japanese_level,
										:first_language,
										:message,
										:need_to_bring,
										:background,
										:detailed_place_1,
										:detailed_place_2,
										:detailed_place_3,
										:detailed_address_1,
										:detailed_address_2,
										:detailed_address_3,
										:other_language,
										language_teachers_attributes: [:id, :language_id, :teacher_id, :_destroy]
									)
  end

  def correct_user
    teacher = Teacher.find(params[:id])
      unless teacher.id == current_user.id
        redirect_to teacher_path(current_user)
      end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<%= render 'shared/category', user: @user, student: @student %>
<div class="col-lg-8">
	<div class="user_info">
		<div class="user_info_text">
			<h2>先生情報更新</h2>
		</div>
		<%= form_for(@teacher, url: teacher_path) do |f| %>
			<div class="container">
		   				    <div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>教える言語</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
							        		<%= nested_form_for @teacher do |n| %>
								        		<%= n.fields_for :language_teachers do |lt| %>
									        		<%= lt.collection_select :language_id, Language.all, :id, :language_name %>
									         	  	<%= lt.link_to_remove "削除" %>
									        	<% end %>
										        <%= n.link_to_add "言語追加", :language_teachers %>
									        <% end %>
						    			</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>教えるその他の言語</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
				    						<%= f.text_field :other_language, class: "form-control", placeholder:"例:タガログ、モンゴル", style: "width:300px; margin:0 auto;" %>
						    			</div>
				    			</div>
				    		</div>
		   				    <div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>母国語</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
				        					<%= f.collection_select(:first_language, Language.all, :language_name, :language_name) %>
						    			</div>
				    			</div>
				    		</div>
		   				    <div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>値段</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
				  					      	<%= f.select :budget, {"1500円" => "1500", "2000円" => "2000", "2500円" => "2500", "3000円" => "3000", "3500円" => "3500", "4000円" => "4000", "4500円" => "4500", "5000円" => "5000"} %>
						    			</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>日本語レベル</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
				       					 	<%= f.select :japanese_level,Teacher.japanese_levels.keys %>
						    			</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>生徒の持ち物</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
								        	<%= f.text_field :need_to_bring, class: "form-control" %>
						    			</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>かんたんな経歴・メッセージなど</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
				    						<%= f.text_area :message, class: "form-control", style: "width:300px; margin:0 auto;" %>
						    			</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所1</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<%= f.text_field :detailed_place_1, class: "form-control", style: "width:300px; margin:0 auto;" %>
				   				    	</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所1の住所</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<%= f.text_area :detailed_address_1, class: "form-control" %>
				   				    	</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所2</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<%= f.text_field :detailed_place_2, class: "form-control", style: "width:300px; margin:0 auto;" %>
				   				    	</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所2の住所</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<%= f.text_area :detailed_address_2, class: "form-control" %>
				   				    	</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所3</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<%= f.text_field :detailed_place_3, class: "form-control", style: "width:300px; margin:0 auto;" %>
				   				    	</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-9  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所3の住所</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<%= f.text_area :detailed_address_3, class: "form-control" %>
				   				    	</div>
				    			</div>
				        	<%= f.hidden_field :user_id, :value => current_user.id %>
				    		<%= f.submit "送信", class: "btn btn-black" %>
			          	</div>
			</div>
	 	<% end %>
	</div>
</div>
<!-- 部分テンプレート閉じタグ -->
</div>

app/views/teachers/index.html.erb
<%= render 'shared/category' %>
	<div class="col-lg-8">
		<div class="mobile_search_button">
    	    <button type="button" class="btn btn-success" data-toggle="collapse" data-target="#mobile_search" style="width: 100%;" >
        		<p style="text-align:center; margin:0 auto;">先生を絞込検索</p>
        	</button>
        </div>
		<div id="mobile_search" class="collapse">
			<div class="dropdown">
				<div class="mobile_search_box">
					<%= search_form_for(@q, :url => {:controller => '/teachers', :action => 'index'}) do |f| %>
							<div class="col-lg-12">
								<div class="col-lg-5">
									<h5>地域で探す</h5>
										<%= f.collection_select :user_areas_id_eq, Area.all, :id, :area_name, include_blank: '選択してください' %>
									<h5>詳細地域を入力</h5>
				          				<%= f.search_field :detailed_address_1_or_detailed_address_2_or_detailed_address_3_cont, class: "form-control search_form", placeholder: "その他の市・町など" %>
				      			</div>
				      			<div class="col-lg-4">
									<h5>言語で探す</h5>
										<%= f.collection_radio_buttons :languages_id_eq, Language.all, :id, :language_name %>
									<h5>その他の言語</h5>
									<div class="form-inline">
										<%= f.search_field :other_language_cont, class: "form-control search_form", placeholder:"例:タガログ" %>語
									</div>
								</div>
								<div class="col-lg-3">
									<h5>値段を選択(/1h)</h5>
									<div class="select">
										<%= f.select :budget_eq, {"1500円" => "1500", "2000円" => "2000", "2500円" => "2500", "3000円" => "3000", "3500円" => "3500", "4000円" => "4000", "4500円" => "4500", "5000円" => "5000"}, include_blank: '選択してください' %>
									</div>
									     	<%= button_tag :type => "submit", :class =>" search-button fa fa-search" do %>
					      					<% end %>
					      		</div>
					      	</div>
			 		<% end %>
			 	</div>
		 	</div>
	 	</div>
		<div class="search_box">
					<%= search_form_for(@q, :url => {:controller => '/teachers', :action => 'index'}) do |f| %>
					<!-- 　チェックボックスが長過ぎるのでやめ -->
						<%#= f.collection_check_boxes(:areas_id_in, Area.all, :id, :area_name) do |b| %>
							<%#= b.label {b.check_box + b.text} %>
						<%# end %>
					<h4 style="margin:0 auto;">先生を検索</h4>
					<div class="col-lg-12">
						<div class="col-lg-5">
							<h5>地域で探す</h5>
								<%= f.collection_select :user_areas_id_eq, Area.all, :id, :area_name, include_blank: '選択してください' %>
							<h5>詳細地域を入力</h5>
                  				<%= f.search_field :detailed_address_1_or_detailed_address_2_or_detailed_address_3_cont, class: "form-control search_form", placeholder: "その他の市・町など" %>
              			</div>
              			<div class="col-lg-4">
							<h5>言語で探す</h5>
								<%= f.collection_radio_buttons :languages_id_eq, Language.all, :id, :language_name %>
								<%#= f.collection_check_boxes(:languages_id_in, Language.all, :id, :language_name) do |b|  %>
									<%#= b.label {b.check_box + b.text} %>
								<%# end %>
							<h5>その他の言語</h5>
							<div class="form-inline">
								<%= f.search_field :other_language_cont, class: "form-control search_form", placeholder:"例:タガログ" %>語
							</div>
						</div>
						<div class="col-lg-3">
							<h5>値段を選択(/1h)</h5>
							<div class="select">
								<%= f.select :budget_eq, {"1500円" => "1500", "2000円" => "2000", "2500円" => "2500", "3000円" => "3000", "3500円" => "3500", "4000円" => "4000", "4500円" => "4500", "5000円" => "5000"}, include_blank: '選択してください' %>
							</div>
       					     	<%= button_tag :type => "submit", :class =>" search-button fa fa-search" do %>
			      				<% end %>
			      		</div>
			      	</div>
	     		<% end %>
		</div>
	<% if @teachers.present? %>
		<% @teachers.each do |t| %>
				<div class="col-lg-4">
					<div class="index_box">
						<div class="index_img">
						<%= link_to teacher_path(t) do %>
							<%= attachment_image_tag t.user,:image, class:"index_img", fallback: "No_img.jpg" %>
						<% end %>
						</div>
						<table>
							<tr>
								<td><div class="fa fa-user"><%= t.user.nickname %>
								</td>
							</tr>
							<tr>
								<td>
									<div class="message_container">
										<div class="fa fa-comment"><%= truncate(t.message, length: 50) %>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									値段：<%= t.budget %>円(1h)
								</td>
							<tr>
							<tr>
								<td>
									言語:
									<% t.language_teachers.each do |lt| %>
									<%= lt.language.language_name %>,
									<% end %>
								</td>
							</tr>
							<tr>
								<td>
									<% unless @requests.exists?(student_id: current_user.id, teacher_id: t.id) %>
										<%= form_for(@request_t, url: teacher_requests_path(t.id), method: :post) do |f| %>
										<%=  f.hidden_field :student_id, :value => current_user.id %>
										<%= f.hidden_field :teacher_id, :value => t.id %>
										<%= f.hidden_field :status, :value => "保留" %>
										<%= f.hidden_field :receiver_id, :value => t.id %>
										<%= f.hidden_field :send_user_id, :value => current_user.id %>
										<%= f.submit "メッセージリクエストを送る", class:"btn btn-blue" %>
										<% end %>
									<% else %>
										<div class="requested_button">
											<h5>メッセージリクエスト受信・送信済</h5>
										</div>
									<% end %>
								</td>
							</tr>
						</table>
					</div>
				</div>
			<% end %>
			<div class="pagination">
				<%= paginate @teachers %>
			</div>
	<% else %>
		<div class="flash_message">
			条件に合う先生は見つかりませんでした
		</div>
	<% end %>

app/views/teachers/new.html.erb
<%= render 'shared/category', user: @user, student: @student %>
<div class="col-lg-8">
	<div class="user_info">
		<div class="user_info_text">
			<h2>先生情報登録</h2>
		</div>
		<% if @teacher.errors.any? %>
		 　<script type="text/javascript">
		 　　<% @teacher.errors.full_messages.each do |f| %>
		　　　　　toastr['<%='error'%>']('<%=f %>');
		 　　<% end %>
		 <% end %>
		　　</script>
		<%= form_for(@teacher, url: user_teachers_path) do |f| %>
			<div class="container">
		   				    <div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>教える言語</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
							        		<%= nested_form_for @teacher do |n| %>
								        		<%= n.fields_for :language_teachers do |lt| %>
									        		<%= lt.collection_select :language_id, Language.all, :id, :language_name %>
									         	  	<%= lt.link_to_remove "削除" %>
									        	<% end %>
										        <%= n.link_to_add "言語追加", :language_teachers %>
									        <% end %>
						    			</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>教えるその他の言語</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
				    						<%= f.text_field :other_language, class: "form-control", placeholder:"例:タガログ、モンゴル", style: "width:300px; margin:0 auto;" %>
						    			</div>
				    			</div>
				    		</div>
		   				    <div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>母国語</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
				        					<%= f.collection_select(:first_language, Language.all, :language_name, :language_name) %>
						    			</div>
				    			</div>
				    		</div>
		   				    <div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>値段</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
				  					      	<%= f.select :budget, {"1500円" => "1500", "2000円" => "2000", "2500円" => "2500", "3000円" => "3000", "3500円" => "3500", "4000円" => "4000", "4500円" => "4500", "5000円" => "5000"} %>
						    			</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>生徒の持ち物</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
								        	<%= f.text_field :need_to_bring, class: "form-control",style:"width:300px; margin:0 auto;" %>
						    			</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>日本語レベル</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
				       					 	<%= f.select :japanese_level,Teacher.japanese_levels.keys %>
						    			</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>かんたんな経歴・メッセージなど</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
				    						<%= f.text_area :message, class: "form-control", style:"width:300px; margin:0 auto;" %>
						    			</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所1</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<label><%= f.text_field :detailed_place_1, style: "width:300px; margin:0 auto;", class: "form-control"%></label>
				   				    	</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所1の住所</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<label><%= f.text_area :detailed_address_1, class: "form-control" %></label>
				   				    	</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所2</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<label><%= f.text_field :detailed_place_2, style: "width:300px; margin:0 auto;", class: "form-control" %></label>
				   				    	</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所2の住所</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<label><%= f.text_area :detailed_address_2, class: "form-control" %></label>
				   				    	</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所3</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<label><%= f.text_field :detailed_place_3, style: "width:300px; margin:0 auto;", class: "form-control" %></label>
				   				    	</div>
				    			</div>
				    		</div>
				    		<div class="col-sm-8  col-sm-offset-2">
						        <div class="form-group">
			   				    		<div class="col-sm-3">
				   				    		<label>場所3の住所</label>
				   				    	</div>
				   				    	<div class="col-sm-9">
											<label><%= f.text_area :detailed_address_3, class: "form-control" %></label>
				   				    	</div>
				    			</div>
				        	<%= f.hidden_field :user_id, :value => current_user.id %>
				    		<%= f.submit "送信", class: "btn btn-black" %>
			          	</div>
			</div>
	 	<% end %>
	</div>
</div>
<!-- 部分テンプレート閉じタグ -->
</div>

app/views/teachers/show.html.erb
<%= render 'shared/category' %>
<div class="col-lg-10">
	<% if Teacher.exists?(id: params[:id]) %>
	<div class="teacher_info">
		<div class="teacher_info_text">
		<h2><i class="fa fa-address-card icon-color"></i><%= @teacher.user.nickname %>さんの先生情報</h2>
		</div>
		<div class="col-lg-5">
			<div class="user_img">
			  <%= attachment_image_tag @teacher.user,:image %>
				<% unless @teacher.id == current_user.id %>
						<% if @teacher.favorited_by?(current_user) %>
						  <div>
						    <%= link_to teacher_favorites_path(@teacher), method: :delete do %>
						      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
						      <%= @teacher.favorites.count %> いいね
						    <% end %>
						  </div>
						<% else %>
						  <div>
						    <%= link_to teacher_favorites_path(@teacher), method: :post do %>
						      <i class="fa fa-heart-o" aria-hidden="true"></i>
						      <%= @teacher.favorites.count %> いいね
						    <% end %>
						  </div>
						 <% end %>
						 <div class="last_login">
							最終ログイン日:<%= @teacher.user.last_sign_in_at.strftime('%Y/%m/%d') %>
						</div>
				<% end %>
				<% if @teacher.id == current_user.id %>
					<%= link_to edit_teacher_path(current_user) do %>
						<div class="btn btn-black">編集</div><br>
					<% end %>
				    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
				    <%= @teacher.favorites.count %> いいね
				<% end %>
			</div>
		</div>
		<div class="col-lg-7">
			<div class="infomation_box">
				<div class="t-header">
					<% @teacher.user.user_areas.each do |t| %>
						<h5>
							<div class="area_box" %>
							<%= t.area.area_name %><br>
							<%= t.area.area_name_eng %>
							</div>
						</h5>
					<% end %>
				</div>
				<div class="col-lg-12 t-information">
						<div class="col-lg-4">
					        <h3><i class="fa fa-book icon-color"></i>教える言語</h3>
					        <h5>
					        	<% if @teacher.other_language.present? %>
					        		<h5><%= @teacher.other_language %></h5>
					        	<% end %>
					        	<% @teacher.language_teachers.each do |lt| %>
						        		<h5><%= lt.language.language_name %></h5>
					        	<% end %>
					        </h5>
					     </div>
					     <div class="col-lg-4">
					        <h3><i class="fa fa-eye icon-color"></i>値段</h3>
					        <h5>¥<%= number_with_delimiter(@teacher.budget) %></h5>
					     </div>
					     <div class="col-lg-4">
					     	<h3><i class="fa fa-comment icon-color"></i>母国語</h3>
					     	<h5><%= @teacher.first_language %></h5>
							<h6>(日本語):<%= @teacher.japanese_level %></h6>
					     </div>
				</div>
				<div class="col-lg-12 t-background">
						<h3>メッセージ・経歴</h3>
						<h5><%= @teacher.message %></h5><br>
				      	<h5><%= @teacher.background %></h5>
				</div>
				<div class="col-lg-12 t-bring">
				      	<h3>持ち物</h3>
				      	<h5><%= @teacher.need_to_bring %></h5>
				</div>
				<div class="col-lg-12 t-places">
					<div class="t-place-1">
				        <h3><i class="fa fa-building icon-color"></i>場所 1</h3>
				        <h5><%= @teacher.detailed_place_1 %><h5><br>
				        <h5><%= @teacher.detailed_address_1 %></h5>
				    </div>
					<div class="t-place-2">
				      	<h3><i class="fa fa-building icon-color"></i>場所 2</h3>
				        <h5><%= @teacher.detailed_place_2 %></h5><br>
				        <h5><%= @teacher.detailed_address_2 %></h5>
				    </div>
				    <div class="t-place-3">
				      	<h3><i class="fa fa-building icon-color"></i>場所 3</h3>
				        <h5><%= @teacher.detailed_place_3 %></h5><br>
				        <h5><%= @teacher.detailed_address_3 %></h5></td>
				    </div>
				</div>
			</div>
		</div>
		</div>
	<% else %>
		<div class="user_info">
		<div class="user_info_text">
			登録された先生情報がありません。
			<%= link_to new_user_teacher_path(current_user) do %>
			<p>先生情報登録</p>
			<% end %>
		</div>
		</div>
	<% end %>
</div>
<!-- container-fluid divタグ閉じ -->
</div>